---
- hosts: localhost 
  gather_facts: false
  vars_files:
      ./vars/vcenter_vars.yaml

  tasks:
    - name: Gather information about all datacenters
      community.vmware.vmware_datacenter_info:
        hostname: '{{ vcenter_server }}'
        username: '{{ vcenter_user }}'
        password: '{{ vcenter_pass }}'
        validate_certs: no
      delegate_to: localhost




